### ISSUE TITLE
Review the english language strings and try to improve them

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kordan/moodle-mod_surveypro#386] opened 2017-10-14 16:10 UTC
Hi,
I am trying to make some surveypro examples for the Moodle documentation. While doing it, I saw some English language strings that I think could be re-written, so that a novel user (me) could better understand what he/she is expected to do.
As I have never before used GitHb, I will likely make quite a few mistakes with the pull requests, and quite likely use a wrong ettiquette. Please be patient with  me. I am only trying to help improve a bit an already great plugin.

Is this acceptable ?

**Comment by kordan** [comment] 2017-10-16 08:09
Of course it is acceptable. Moreover, it is welcome.

**Comment by kordan** [comment] 2017-10-27 06:51
Closed as fixed as already merged few days ago.

**Closed by kordan** 2017-10-27 06:51 UTC

**Comment by stronk7** [comment] 2017-10-28 08:56
For reference, it uses to be a good idea to make reference, in the commit message, to the issue number, for example: 

```
Rewrite in a more understandable way. Fixes #386
```

That way, the pull request shows the linked issue and the issue is auto closed when the pull request is merged. And both (pull requests and issue) remain nicely linked and you can know what fixes what.

Just a tiny tip that helps keeping the 2 lists well synced... thanks!

**Comment by germanvaleroelizondo** [comment] 2017-10-30 04:28
Gracias Eloy !
