### ISSUE TITLE
Error in Search

### ISSUE THREAD

**Issue by martinvivek** [kordan/moodle-mod_surveypro#321] opened 2017-02-16 15:00 UTC
When i click on the search i Got an Error as follows:

This page did not call $PAGE->set_url(...). Using  #http://website.com/mod/surveypro/view_search.php
line 565 of \lib\pagelib.php: call to debugging()
line 773 of \lib\pagelib.php: call to moodle_page->magic_get_url()
line 507 of \local\usertours\classes\manager.php: call to moodle_page->__get()
line 460 of \local\usertours\classes\helper.php: call to local_usertours\manager::get_current_tour()
line 61 of \local\usertours\lib.php: call to local_usertours\helper::bootstrap()
line 1303 of \lib\navigationlib.php: call to local_usertours_extend_navigation()
line 3472 of \lib\navigationlib.php: call to global_navigation->initialise()
line 723 of \lib\pagelib.php: call to settings_navigation->__construct()
line 773 of \lib\pagelib.php: call to moodle_page->magic_get_settingsnav()
line 136 of \blocks\settings\block_settings.php: call to moodle_page->__get()
line 288 of \blocks\moodleblock.class.php: call to block_settings->get_content()
line 230 of \blocks\moodleblock.class.php: call to block_base->formatted_contents()
line 976 of \lib\blocklib.php: call to block_base->get_content_for_output()
line 1028 of \lib\blocklib.php: call to block_manager->create_block_contents()
line 476 of \lib\outputrenderers.php: call to block_manager->ensure_content_created()
line 38 of \theme\essential\layout\redirect.php: call to core_renderer->standard_head_html()
line 1028 of \lib\outputrenderers.php: call to include()
line 958 of \lib\outputrenderers.php: call to core_renderer->render_page_layout()
line 894 of \lib\outputrenderers.php: call to core_renderer->header()
line 2821 of \lib\weblib.php: call to core_renderer->redirect_message()
line 71 of \mod\surveypro\view_search.php: call to redirect()

**Comment by kordan** [comment] 2017-03-25 10:10
Thanks for the report.
I'll do all my best to fix it since next monday.
Maybe I will you ask for some more details.

**Comment by kordan** [comment] 2017-03-29 12:18
Ciao Martinvivek.
There is no way for me to reproduce this issue.
Did you update your code to the last available release?
Which version are you using?
Are you still experiencing this issue?

**Comment by kordan** [comment] 2017-07-10 04:56
Issue has been closed as martin vivek seems disappeared and without him the issue can't be reproduced.

**Closed by kordan** 2017-07-10 04:56 UTC
